### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#415]
# Milestone 1 - Whats next for Curio

The current state of the project represents our initial efforts to make curio an effective tool. Given early feedback and what we have learned so far we are now working towards our first major release.

- [x] **Privacy report** - This is a new report designed to act as the basis for compliance documentation.
  - [x] https://github.com/Bearer/curio/issues/398 
- [x] **Deeper rules** - We recognize that one of the easiest ways to leak data is through loggers and analytics tools. To this end, we want to expand some of our existing policies to work with more providers.
  - [x] https://github.com/Bearer/curio/issues/366
  - [x] https://github.com/Bearer/curio/issues/459
- [x] **Architecture refactor** - Writing policies needs to be accessible and straightforward so we are working to improve this process while improving overall performance.
  - [x] https://github.com/Bearer/curio/pull/308
- [x] **JS** - For our first major release we want to support policy output for Ruby and Javascript.
  - [x] https://github.com/Bearer/curio/issues/431
  - [x] https://github.com/Bearer/curio/issues/504
- [x] **GitHub action** - We want to provide a basic action so people can easily incorporate curio into their CI workflow.
  - [x] https://github.com/Bearer/curio-action/issues/2
- [x] **Battle test summary report** - Curio's detection capability has been calibrated by running against many open-source projects. This update to our testing flow will mean we can verify the policy report is what we expect and allow us to remove any false positives before release while providing a baseline for future improvements.
  - [x] https://github.com/Bearer/curio/issues/353 
- [x] **Improved UX** Some ideas we have had from feedback to make curio more usefull
  - [x] https://github.com/Bearer/curio/issues/442
  - [x] https://github.com/Bearer/curio/issues/441
  - [x] https://github.com/Bearer/curio/issues/432
  - [x] https://github.com/Bearer/curio/issues/424
