### ISSUE TITLE
Milestone 2 - Rename and OWASP top 10

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#604]
We originally started with our own DSR's naming system but found CWE's are more relatable to end users so these will be used going forward. Next, while we intially focused on more data related aspects a general coverage of the [OWASP top 10 ](https://owasp.org/www-project-top-ten/) is needed to round out the project as a strong SAST tool. As a result we now aim to increase coverage in these areas for both Ruby and JS.

As well of as the above we have decided to rename Curio into simply Bearer, the name of the company supporting it.
The reasoning is simple, it will be easier to communicate and allow anyone to quickly identify the company behind. No doubt you've seen plenty of "X Product by Y Company" tools and we want to avoid this.

- [x] **Support CWE's summary output and documentation**
  - [x] https://github.com/Bearer/curio/issues/600
  - [x] #605
  - [x] https://github.com/Bearer/bearer/issues/728
- [x] **OWASP top 10**
  - [x] https://github.com/Bearer/curio/issues/573
  - [x] https://github.com/Bearer/curio/issues/606
- [x] **Project Rename**
  - [x] https://github.com/Bearer/bearer/pull/616
  - [x] rename repo to bearer
  - [x] https://github.com/Bearer/bearer/pull/620
  - [x] https://github.com/Bearer/curio/pull/609
  - [x] https://github.com/Bearer/bearer/pull/625
  - [x] https://github.com/Bearer/bearer/pull/628
  - [x] #629
  - [x] #607
  - [x] update websites staging/preview/live (ghpages+netlify)
  - [x] update action
    - https://github.com/marketplace/actions/bearer-security

**Comment by gotbadger** [comment]
with the release of version v1.0.0 this is now complete
