### ISSUE TITLE
Milestone 3 - scan and rule improvements

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#766]
We've been working on rules for the last few weeks and over that time we've come up with lots of ideas on how to improve things, for the next few weeks we will focus on these areas:

- [x] **Improve rules experience**
  - [x] Improve trigger in rule syntax https://github.com/Bearer/bearer/issues/744
  - [x] Improve custom rule validation and error handling https://github.com/Bearer/bearer/issues/545
  - [x] Allow rules to be skipped from code comments https://github.com/Bearer/bearer/issues/788
  - [x] Load rules dynamically https://github.com/Bearer/bearer/issues/799
    - [x] Improve rule integration testing workflows
    - [ ] ~~Allow rule behaviours to be shared~~
  - [ ] ~~Add library data to rules doc https://github.com/Bearer/bearer/issues/639~~
- [x] **Strengthen scanning**
  - [ ] ~~Stop using tree sitter queries for patterns~~
    - https://github.com/Bearer/bearer/issues/790
  - [x] Strengthen detections
  - [x] Change rule language to allow equality of sub-patterns #829
  - [x] Add Typescript support https://github.com/Bearer/bearer/issues/543
  - [ ] ~~Diff scan support~~
  - [ ] ~~New battle test to produce metrics against nodeGoat / RailsGoat / juicy app projects so we can gauge improvements over time~~

**Comment by gotbadger** [comment]
This milestone is now complete we have moved diff scan and updated battle report to next milestone.
