### ISSUE TITLE
Improve rules

### ISSUE THREAD

**Issue by vjerci** [Bearer/bearer#819]
[Juice shop](https://github.com/juice-shop/juice-shop) is owasp project in typescript that we can use to detect various vulnerabilities. For most vulnerabilities we have rules, but for some, they are not triggering.

## TODO:
- [x] Fix dataflow bug where we have multiple entries for the duplicate detections  (affected rule: `javascript_weak_encryption` and probably many more) https://github.com/Bearer/bearer/pull/834
     - [x] Improve dataflow
     - [x] Improve rego to handle dataflow changes
          - [x] handle presence failures
          - [x] handle local datatype failures
          - [x] handle global datatype failures
     - [x] filter rules based on same parent
     - [x] Make sure there are 2 vulnerabilities reported for  multiple datatypes on same line number
     - [x] Open issue for severity https://github.com/Bearer/bearer/issues/832
     - [x] fix risks_test
     - [x] fix security test
     - [x] sort vulnerabilities (results from opa, as opa messes up the ordering)
- [ ] merge rule `ruby_lang_http_insecure` with `ruby_lang_http_post_insecure_with_data` https://github.com/Bearer/bearer/issues/822
- [x] There are a lot of crashes due to nil pointer for typescript

**Comment by vjerci** [comment]
closing this as big chunk of it is done and remaining tasks are split in seperate issues
