### ISSUE TITLE
Milestone 4 - Java and KPI's

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#887]
Heres what we will be working on in the next few weeks. As always we will release things as they are completed.

- [x] **Battle test KPI's** - We've been improving rules over the last few weeks but we want to shine a bit more light on the progress we are making. In this milestone we will rework our "battle testing" process we do before each to generate a set of KPI's. Initally we will focus on a mix of security projects like [NodeGoat](https://github.com/Bearer/NodeGoat) and other large open source projects. 
  - [x] Improve rules based on KPI projects
- [x] **Java Language Support** - We've decided on this for our next language as Java codebases are present in many large orgs where we think Bearer can really make a diffrence.
   - https://github.com/Bearer/bearer/issues/894
- [ ] ~~**Diff Scan** - We aim to get a basic version of this released as we move towards having more fully featured PR support.~~

**Comment by gotbadger** [comment]
With the most recent improvements to rules I think we can close this out for now
