### ISSUE TITLE
Java Language Support

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#894]
For our next language we intend to support Java with a focus on struts, hibernate and the spring framework for the intial rules. We will also use https://github.com/Bearer/WebGoat as a baseline for testing during development.

We can also use https://owasp.org/www-project-benchmark/ to see how we are doing.

### Tasks
- [x] Add java language support
    - [x] Add language support
    - [x] Add Detectors support
       - [x] add string support
       - [x] add objects support
- [x] Write 2 rules for java
    - [x] Write logger rule
        - [x] Add a script for development purposes(running a single rule locally with the local bearer version)
        - [x] Handle case when object definition is passed down through variable
        - [x] Handle case when the auxiliary rule is defined as class properties
    - [x] Enable debugging
    - [x] Write sql injection rule
- [x] Make sure nothing crashes when scanning projects
    - [x] Scan https://owasp.org/www-project-benchmark/
    - [x] Scan https://github.com/Bearer/WebGoat 
    - no crash beside the javascript/typescript parser working on external libraries (perhaps we should globally exclude`/lib` from scans?)
- [x] Write docs on what can be improved in Java (go through java lang specs and see what we can't detect)
